---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  description: Clone a git repository
  workspaces:
    - name: source
  params:
    - name: url
      description: Repository URL
      type: string
    - name: revision
      description: Git revision
      type: string
      default: main
  steps:
    - name: clone
      image: alpine/git:latest
      workingDir: $(workspaces.source.path)
      script: |
        set -e
        git clone --depth 1 --branch $(params.revision) $(params.url) .

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8
spec:
  description: Lint Python code with flake8
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to flake8
      type: string
      default: "--count --select=E9,F63,F7,F82 --show-source --statistics"
  steps:
    - name: lint
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        set -e
        python -m pip install --upgrade pip
        pip install flake8
        flake8 . $(params.args)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  description: Build a container image using Buildah
  workspaces:
    - name: source
  params:
    - name: image-name
      description: Image name
      type: string
    - name: dockerfile
      description: Path to Dockerfile
      type: string
      default: Dockerfile
  steps:
    - name: build
      image: quay.io/buildah/stable:latest
      workingDir: $(workspaces.source.path)
      securityContext:
        privileged: true
      script: |
        set -e
        buildah bud -f $(params.dockerfile) -t $(params.image-name) .

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: oc-deploy
spec:
  description: Deploy application to OpenShift
  params:
    - name: app-name
      description: Application name
      type: string
    - name: build-image
      description: Built image
      type: string
  steps:
    - name: deploy
      image: quay.io/openshift/origin-cli:latest
      script: |
        set -e
        oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
